### ISSUE TITLE
Swift and Core Data assets not being renamed

### ISSUE THREAD

**Issue by lee-leonardo** [pwa-builder/pwabuilder-MacOS#10]
Looking at the output of the project, it looks like the assets for the MacOS doesn't rename the Core Data and Swift assets within the project.

- `MacOSpwa.xcdatamodeld`
- `MacOSpwaTests.swift`
- `MacOSpwaUITests.swift`

I find it doubtful that a PWA would rely or use a Core Data database nor would have Swift code within the application. 

Thinking this either should be removed from the project or renamed appropriately.

Is anyone using this and thoughts?

**Comment by JudahGabriel** [comment]
I have no objection to removing those bits. @Rumsha7 - thoughts?

**Comment by Rumsha7** [comment]
I have no objections to removing those bits. @lee-leonardo before committing the change, would you be able to test and double check that the app is still successfully created when those are removed?

**Comment by lee-leonardo** [comment]
issue is resolved as of 0.3.5
