### ISSUE TITLE
Generated Xcode project cannot be opened

### ISSUE THREAD

**Issue by navanchauhan** [pwa-builder/pwabuilder-MacOS#13]
Issue created on the main pwa-builder project as well, I later came across this repository 

**Describe the bug**
The project appears to be damaged to Xcode and thus I cannot open the project

**To Reproduce**
1. Go to https://www.pwabuilder.com/
2. Enter website URL ( In my case https://navanchauhan.github.io )
3. Click on Build my PWA
4. Download macOS project 
5. Try to Open it

**Expected behavior**
It should have opened the project in Xcode

**Screenshots**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/29234112/83856411-24c2af80-a737-11ea-8c39-0f2707514cdc.png">

**Additional info (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Browser Safari
 - Browser Version 13.1.1

**Additional context**
I have attached the zip file
[projects.zip](https://github.com/pwa-builder/PWABuilder/files/4734929/projects.zip)

Analysing through `xcodebuild`

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list -project mac/MacOSpwa.xcodeproj

2020-06-05 15:47:36.227 xcodebuild[17870:802857] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 154. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2020-06-05 15:47:36.228 xcodebuild[17870:802857] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
xcodebuild: error: Unable to read project 'MacOSpwa.xcodeproj' from folder '/Users/navanchauhan/Desktop/Projects/projects/mac'.
	Reason: The project ‘MacOSpwa’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Path: /Users/navanchauhan/Desktop/Projects/projects/Mac/MacOSpwa.xcodeproj
```

Edit 1:

Okay, so I did a little digging around in the `project.pbxproj` file and the error arises because the strings are not present in double quotes, so if any value has a space in between them like in my case `name = Navan Chauhan;` breaks it. The fix is as easy as adding double quotes. `name = "Navan Chauhan";`

Affected Values that need double quotes:

```
name = Navan Chauhan;
productName = Navan Chauhan;
...

name = Navan ChauhanTests;
productName = MacOSpwaTests; ( This works even without double quotes )

...

name = Navan ChauhanUITests;
productName = MacOSpwaUITests;

...

PRODUCT_NAME = Navan Chauhan;
...
```

Even though making these changes make opening the project in Xcode possible, the build still fails.

The Xcode Project has a reference to a PWAInfo file which is not present in the downloaded folder. The project cannot be built because the copying stage fails as the file does not exist. Removing the reference from within the project navigation fixed this but then the app crashes due to this line of code 

```swift
//TODO: Remove this later --- PWABuilder will load data from manifest
        //Load data from manifest.json to create a manifest object
        if manifest == nil {
            let path = Bundle.main.path(forResource: "PWAinfo/manifest", ofType: "json")
            let url = URL(fileURLWithPath: path!)
            do {
                let jsonData = try Data(contentsOf: url)
                let json = try JSONSerialization.jsonObject(with: jsonData) as! [String:Any]
                manifest = Manifest(json: json)
                webUrl = manifest.getAppStartUrl()
            } catch {
                print(error)
            }
        }
```

If you notice the line

```swift
let path = Bundle.main.path(forResource: "PWAinfo/manifest", ofType: "json")
```

is referencing to a non existent path, the fix is to create a directory called `PWAinfo` and copy the `manifest.json` from the `./source/app/src/main/assets/` to the './PWAinfo' folder inside the mac folder 

Edit: There is no need to remove the reference from the project navigation folder because when you create the PWAinfo folder and copy the `manifest.json` file it builds and runs successfully

**Comment by lee-leonardo** [comment]
Hey Navan,
Thanks for bringing this to our attention!
I'll take a look right away!

**Comment by JudahGabriel** [comment]
Looks like this is the same issue you fixed @lee-leonardo. We just need to deploy the API to production. We expect to do that next week.
