### ISSUE TITLE
Missing PWAInfo compile error

### ISSUE THREAD

**Issue by mixtly87** [pwa-builder/pwabuilder-MacOS#18]
Steps to reproduce:
1. Download the macOS PWA Xcode project from https://www.pwabuilder.com/ for the pinterest.com example app
2. Configure Signing & Capabilites in Xcode so that there are now errors
3. Try building the project
4. Compile error "/Users/me/Downloads/projects/mac/PWAinfo: No such file or directory" is shown.

Expected:
Project should be able to Compile and Run from Xcode.

Actual:
Xcode project cannot be compiled due to the "PWAinfo: No such file or directory" error.

**Comment by JudahGabriel** [comment]
@lee-leonardo is this the same issue you fixed, or something different?

**Comment by rodchalski** [comment]
Having the same issue

**Comment by rodchalski** [comment]
I manually added a folder called PWAinfo inside the mac folder.  And then added manifest.json inside the newly created PWAinfo folder.  It "worked", kind of.  It's buggy / doesn't seem to want to communicate with server, but it runs.

**Comment by JudahGabriel** [comment]
Thanks. We're tracking this issue over at the main repo: https://github.com/pwa-builder/PWABuilder/issues/886

**Comment by santiq** [comment]
Same problem here.

I created the PWAInfo folder and added my manifest.json, now it builds, but it doesn't start.

> Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Seems like an error with my manifest.json?

![Screen Shot 2020-08-06 at 13 21 09](https://user-images.githubusercontent.com/7070683/89556570-fa997680-d7e7-11ea-87b2-0f2ad16779be.png)

**Comment by rodchalski** [comment]
Delete this appScope line that is highlighted and try again.


Rodrigo

**Comment by JudahGabriel** [comment]
We've got a fix for this issue in PR right now. We plan on deploying either today or Monday.

**Comment by lee-leonardo** [comment]
https://github.com/pwa-builder/pwabuilder-MacOS/pull/20

**Comment by lee-leonardo** [comment]
@mixtly87 @rodchalski @santiq the change to resolve this issue has been deployed to the site (#20), thank you for your patience!
