### ISSUE TITLE
Unable to close app on MacOS

### ISSUE THREAD

**Issue by subhash279** [pwa-builder/pwabuilder-MacOS#23]
Hi,
First of all, great work on this. I was able to build my app, submit to apple store and got approved as well!
I just noticed that when I right click on the mac OS app icon in the dock and press "Quit", it doesn't actually close like other native MacOS apps.
May I pls know if I am missing something or if this is a known issue?

Thanks.

**Comment by subhash279** [comment]
as a consequence once the app is open, it can only be closed from task manager. Or else it blocks even the mac shutdown. So pls let me know if this is solvable as it can be a major hurdle for every one as well.

**Comment by peterpeterparker** [comment]
Funny thing, for the same reason / error, Apple rejected  the app I submitted for fun (see msg in  #24)

**Comment by JudahGabriel** [comment]
Hi @subhash279 can you file a bug in the [main PWBuilder repo](https://github.com/pwa-builder/pwabuilder/issues)? That forum is monitored and kept up-to-date by the team. Thanks.

**Comment by peterpeterparker** [comment]
I reported it in the main repo too as I received within the same rejection from Apple this error too 👉 https://github.com/pwa-builder/PWABuilder/issues/1275
