### ISSUE TITLE
Apple rejection msg "This application is not allowed to Print"

### ISSUE THREAD

**Issue by peterpeterparker** [pwa-builder/pwabuilder-MacOS#24]
I submitted an app to the App Store for fun and got reject notably because of two issues flagged as "Performance"

> Guideline 2.1 - Performance
> 
> We discovered one or more bugs in your app when reviewed on Mac running macOS 11.0.1.
> 
> - Selecting App menu> Quit item does not quit the app. 
> - File/Print menu displays a message "This application is not allowed to Print".
> 
> Next Steps
> 
> Please run your app on a device to identify the issue(s), then revise and resubmit your app for review.

"Print issue" is the one reported in this issue, "Quit" has already been reported in https://github.com/pwa-builder/pwabuilder-MacOS/issues/23

Note: this has no priority to me, as I said, only submitted the app for fun / to give it a try, so no rush when it comes to me

**Comment by JudahGabriel** [comment]
Hi @peterpeterparker can you please open a bug on our main [PWABuilder repo](https://github.com/pwa-builder/pwabuilder/issues)? Thanks.

**Comment by peterpeterparker** [comment]
Sure. Done 👉 https://github.com/pwa-builder/PWABuilder/issues/1275
